<div class="container-fluid">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1"> 
            <div id="mg-landing-wrapper">

                <form action="" class="form-horizontal" method="post">

                    <div class="form-group">
                        <label class="col-xs-12 col-sm-2 control-label" for="host">Host</label>
                        <div class="col-xs-12 col-sm-10">
                            <input type="text" class="form-control" name="host" id="host" placeholder="Host here"/>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-xs-12 col-sm-2 control-label" for="database">Database</label>
                        <div class="col-xs-12 col-sm-10">
                            <input type="text" class="form-control" name="database" id="database" placeholder="Database here"/>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-xs-12 col-sm-2 control-label" for="username">Username</label>
                        <div class="col-xs-12 col-sm-10">
                            <input type="text" class="form-control" name="username" id="username" placeholder="Username here"/>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-xs-12 col-sm-2 control-label" for="password">Password</label>
                        <div class="col-xs-12 col-sm-10">
                            <input type="password" class="form-control" name="password" id="password" placeholder="Password here"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-12 col-sm-2 control-label" for="driver">Driver</label>
                        <div class="col-xs-12 col-sm-10">
                            <select class="form-control" name="driver" id="driver">
                                <option value="-1">Please select a driver</option>
                                <?php 
                                    foreach ($this->dbDrivers as $driver => $name) {
                                        echo '<option value="' . $driver . '">' . $name . '</option>';
                                    }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-12">
                            <button type="submit" class="btn btn-primary pull-right btn-lg">Connect</button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>